mode = "dark"

accent = "#686868"
selection = "#686868"
muted = "#525252"

background = "#222222"
dark_background = "#141414"
darker_background = "#0d0d0d"
lighter_background = "#2a2a2a"

foreground = "#ffffff"
dark_foreground = "#8b8b8b"
light_foreground = "#ffffff"
bright_foreground = "#b9b9b9"

hyprland_active_border = "rgba(686868ee) rgba(b9b9b9ee)"
hyprland_inactive_border = "rgba(555555ee)"
active_border_color = "#b9b9b9"
active_tab_background = "#686868"

red = "#7c7c7c"
yellow = "#a0a0a0"
green = "#8b8b8b"
cyan = "#868686"
blue = "#686868"
magenta = "#747474"

bright_red = "#7c7c7c"
bright_yellow = "#a0a0a0"
bright_green = "#8b8b8b"
bright_cyan = "#868686"
bright_blue = "#686868"
bright_magenta = "#747474"
