mode = "dark"

accent = "#b2a28d"
selection = "#d7c8b2"
muted = "#686660"

background = "#100d05"
dark_background = "#090703"
darker_background = "#050402"
lighter_background = "#2d2a23"

foreground = "#d7c8b2"
dark_foreground = "#686660"
light_foreground = "#e3d8c9"
bright_foreground = "#f1d39d"

hyprland_active_border = "rgba(b2a28dee) rgba(f1d39dee)"
hyprland_inactive_border = "rgba(686660ee)"
active_border_color = "#f1d39d"
active_tab_background = "#b2a28d"

red = "#977b7c"
yellow = "#9c917a"
green = "#7c7c64"
cyan = "#9d9d85"
blue = "#b2a28d"
magenta = "#977b7b"

bright_red = "#bf9ea0"
bright_yellow = "#c2b798"
bright_green = "#a0a181"
bright_cyan = "#c2c3a4"
bright_blue = "#dac8ad"
bright_magenta = "#bf9e9e"
