mode = "dark"

accent = "#686868"
selection = "#b9b9b9"
muted = "#525252"

background = "#0f0f0f"
dark_background = "#080808"
darker_background = "#040404"
lighter_background = "#2c2c2c"

foreground = "#b9b9b9"
dark_foreground = "#525252"
light_foreground = "#cecece"
bright_foreground = "#ffffff"

hyprland_active_border = "rgba(686868ee) rgba(ffffffee)"
hyprland_inactive_border = "rgba(525252ee)"
active_border_color = "#ffffff"
active_tab_background = "#686868"

red = "#7c7c7c"
yellow = "#a0a0a0"
green = "#858e6c"
cyan = "#868686"
blue = "#686868"
magenta = "#747474"

bright_red = "#7c7c7c"
bright_yellow = "#a0a0a0"
bright_green = "#8b8b8b"
bright_cyan = "#868686"
bright_blue = "#686868"
bright_magenta = "#747474"
