mode = "dark"

accent = "#92a8b9"
selection = "#c1cae2"
muted = "#61686c"

background = "#060f14"
dark_background = "#03080b"
darker_background = "#020406"
lighter_background = "#242c30"

foreground = "#c1cae2"
dark_foreground = "#61686c"
light_foreground = "#d4daeb"
bright_foreground = "#c5d5ff"

hyprland_active_border = "rgba(92a8b9ee) rgba(c5d5ffee)"
hyprland_inactive_border = "rgba(61686cee)"
active_border_color = "#c5d5ff"
active_tab_background = "#92a8b9"

red = "#967b83"
yellow = "#7e96a5"
green = "#628181"
cyan = "#83a3a2"
blue = "#92a8b9"
magenta = "#967a83"

bright_red = "#be9ea8"
bright_yellow = "#a1bbcf"
bright_green = "#83a6a6"
bright_cyan = "#a5cac8"
bright_blue = "#b6cee4"
bright_magenta = "#be9da9"
