#!/bin/bash
layout=$(hyprctl activeworkspace -j | jq -r '.tiledLayout')
if [[ "$layout" == "scrolling" ]]; then
    hyprctl dispatch layoutmsg consume_or_expel prev
else
    hyprctl dispatch layoutmsg togglesplit
fi
